# Site settings
title: Bojanorama
email: myemail@somewhere.net
description: > # this means to ignore newlines until "baseurl:"
        Ramblings on social science, social networks, statistics, 
        data analysis, computing, game theory and alike.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mbojan
github_username:  mbojan
gems: ['jekyll-pandoc-multiple-formats']

pandoc:
        skip: true
        impose: false
        output: ./tmp
        flags: '--smart'
        site_flags: '--toc'
        outputs:
                pdf: '--latex-engine=pdflatex'

